import { useSearchParams } from 'react-router-dom';
import { AppShell } from '../components/AppShell';
import {
  COVERAGE_MANIFEST,
  coverageOverallStats,
  coverageStatusLabel,
  type CoverageRow,
} from '../lib/mock-data';

function statusClass(status: CoverageRow['status']) {
  return status === 'indexed' ? 'indexed' : status === 'partial' ? 'partial' : 'not-indexed';
}

/* Coverage Explorer — ports ux-design/coverage.html. Reads the same
   coverage_manifest the Ask refusal card reads (§5.4). Deep link
   ?service=<name> highlights a row, as used by the refusal card. */
export function Coverage() {
  const [params] = useSearchParams();
  const highlightService = params.get('service');
  const stats = coverageOverallStats();

  return (
    <AppShell
      title="Coverage Explorer"
      activeNav="coverage"
      topbarRight={<span className="persona-pill">All personas</span>}
    >
      <div className="main-scroll">
        <div className="main-inner">
          <p style={{ color: 'var(--text-dim)', fontSize: 13, marginTop: 0 }}>
            Which services are indexed, at what tier, and when the rest are scheduled. This is the same{' '}
            <code>coverage_manifest</code> data the Ask screen's refusal card reads from — status wording
            is generated by one shared function so the two surfaces never disagree about a service.
          </p>

          <div className="filter-row">
            <select className="mock-select">
              <option>All ARTs</option>
              <option>Payments</option>
              <option>Growth</option>
            </select>
            <select className="mock-select">
              <option>All tiers</option>
              <option>Tier 1+</option>
              <option>Tier 4 only</option>
            </select>
          </div>

          <div className="panel" style={{ overflow: 'hidden' }}>
            <table className="coverage-table">
              <thead>
                <tr>
                  <th>Service</th>
                  <th>Tier reached</th>
                  <th>Last indexed</th>
                  <th>Next scheduled</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {COVERAGE_MANIFEST.map((row) => (
                  <tr key={row.service} className={row.service === highlightService ? 'highlight' : ''}>
                    <td>
                      <strong>{row.service}</strong>
                    </td>
                    <td>{row.tierLabel}</td>
                    <td>{row.lastIndexed ?? '—'}</td>
                    <td>{row.nextScheduled ?? '—'}</td>
                    <td>
                      <span className={`status-pill ${statusClass(row.status)}`}>
                        {coverageStatusLabel(row)}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="overall-stats">
            <div className="overall-stat">
              <div className="num">{stats.pctTier1}%</div>
              <div className="label">services at tier ≥ 1</div>
            </div>
            <div className="overall-stat">
              <div className="num">{stats.pctTier4}%</div>
              <div className="label">services at tier 4 (flow)</div>
            </div>
            <div className="overall-stat">
              <div className="num">{stats.total}</div>
              <div className="label">services in manifest</div>
            </div>
          </div>

          <p className="mock-note">
            Deep link example: <code>/coverage?service=checkout-svc</code> (as used by the Ask screen's
            refusal card) highlights the matching row.
          </p>
        </div>
      </div>
    </AppShell>
  );
}
